#!/bin/bash

# Function to handle a single ROM file
process_rom() {
    local romfile=$1

    # Compute SHA-1 hash of the file
    ROMHASH=$(sha1sum -b "$romfile" 2>> log.txt | awk '{ print $1 }') || { echo "Error: Failed to compute SHA-1 hash" >> log.txt; return 1; }

    # Remap v64 and n64 hashes to their z64 hash equivalent
    case "$ROMHASH" in
    ef6d7273a7bc1cbf778f9021753db5efddfe495e) ROMHASH=7f5630dbc4d5d61d6276213210c4d5cdd83a47d6 ;; # v64
    991460c32f53c7bb0bc650baf5a40ffde6165840) ROMHASH=7f5630dbc4d5d61d6276213210c4d5cdd83a47d6 ;; # n64
    22f8bfa1ab6c763013a3c2a568bb014395b12499) ROMHASH=d6133ace5afaa0882cf214cf88daba39e266c078 ;; # v64
    1a26735c63cb3bdf5eb32d21acf774ee6724f227) ROMHASH=d6133ace5afaa0882cf214cf88daba39e266c078 ;; # n64
    8c378b87c83b3f4de20b14accf91e7590399f5dc) ROMHASH=9743aa026e9269b339eb0e3044cd5830a440c1fd ;; # v64
    8b0436e540b95a5353969d4ee360273cf33fb659) ROMHASH=9743aa026e9269b339eb0e3044cd5830a440c1fd ;; # n64
    esac

    case "$ROMHASH" in
    7f5630dbc4d5d61d6276213210c4d5cdd83a47d6) ROM=N64_US;;
    d6133ace5afaa0882cf214cf88daba39e266c078) ROM=N64_US;;
    9743aa026e9269b339eb0e3044cd5830a440c1fd) ROM=GC_US;;
    *)
        echo "$ROMHASH rom hash does not match: $ROMHASH" | tee -a $LOGFILE
        return 1
        ;;
    esac

    OTRNAME="mm.o2r"
    if [ ! -e "$GAMEDIR/$OTRNAME" ]; then
        echo "Generating $OTRNAME from $romfile..." | tee -a $LOGFILE
        ./assets/extractor/ZAPD.out ed -eh -i ./assets/xml/$ROM -b ./$romfile -fl ./assets/extractor/filelists -o placeholder -osf placeholder -gsf 1 -rconf ./assets/extractor/Config_$ROM.xml -se OTR --otrfile "$OTRNAME" --portVer "2.0.0"
        if [ $? -eq 0 ]; then
            echo "Successfully generated $OTRNAME"
        else
            echo "Error: Failed to generate $OTRNAME."
            return 1
        fi
    fi
}

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export LD_LIBRARY_PATH="$GAMEDIR/libs:$LD_LIBRARY_PATH"

# Extract extractor directory
if [ -f assets/extractor.zip ]; then
    echo "Extracting xml files..."
    cd assets
    if unzip -oq extractor.zip; then
        rm extractor.zip
        cd ..
    fi
fi

# Count the number of ROM files
rom_count=0
for romfile in *.*64; do
    if [ -f "$romfile" ]; then
        rom_count=$((rom_count + 1))
    fi
done

sleep 1
echo "Found $rom_count ROM files!"

# Process them all
counter=1
processed_any_rom=0

for romfile in *.*64; do
    if [ -f "$romfile" ]; then
        echo "Processing ${romfile}..."
        mv "$romfile" "rom${counter}.z64"
        if [ $? -eq 0 ]; then
            process_rom "rom${counter}.z64"
            if [ $? -eq 0 ]; then
                processed_any_rom=1
                counter=$((counter + 1))
            else
                echo "Error: process_rom failed for rom${counter}.z64"
            fi
        else
            echo "Error: Failed to rename $romfile"
        fi
    fi
done

# Conditional cleanup
if [ "$processed_any_rom" -eq 1 ]; then
    echo "Cleaning up..."
    rm -rf ./placeholder
    rm -rf *.*64
fi

echo "Finished processing all ROM files."
echo "Patching process complete!"